repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown, css, scss]
        additional_dependencies:
          - prettier@3.1.0
          - prettier-plugin-svelte@3.1.2
        files: \.(js|jsx|ts|tsx|json|yaml|yml|md|css|scss|svelte)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.15.0
    hooks:
      - id: eslint
        files: \.(js|ts|svelte)$
        types: [file]
        additional_dependencies:
          - eslint@9.15.0
          - eslint-plugin-svelte@2.46.1
          - typescript-eslint@8.15.0
          - "@eslint/js@9.15.0"
          - globals@15.12.0
